export const VIOLATIONS_DISTANCE = "VIOLATIONS_DISTANCE";
export const VIOLATIONS_DURATION = "VIOLATIONS_DURATION";
export const MOTION = "MOTION";
export const INTIALIZE_IN = "INTIALIZE_IN";
export const SELECTED_CAMERA = "SELECTED_CAMERA";
export const SELECTED_ZONE = "SELECTED_ZONE";
